import { AppProvider } from "@/components/AppContext";
import { Roboto } from "next/font/google";
import Sidenav from "../components/sidebar/Sidenav";
import Navbar from "../components/navbar/Navbar";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Meal Deal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppProvider>
          <main className="main">
            <Sidenav />
            <section className="bg-bg right-side flex-1">
              <Navbar />
              {children}
            </section>
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
