import { Roboto } from "next/font/google";
import "./globals.css";
import Sidenav from "@/components/sidebar/Sidenav";
import Navbar from "@/components/navbar/Navbar";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Meal Deal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="main">
          <Sidenav />
          <section className="bg-bg">
            <Navbar />
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
