import { AppProvider } from "@/components/AppContext";
import { Roboto } from "next/font/google";
import Sidenav from "@/components/sidebar/Sidenav";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Meal Deal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="main">
          <AppProvider>
            <Toaster />
            <Sidenav />
            <section className="bg-bg right-side flex-1">
              <Navbar />
              {children}
            </section>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
